### ISSUE TITLE
Is this "Nix on Genode" or is this "NixOS on Genode"?

### ISSUE THREAD

**Issue by spacekitteh** [ehmry/genode-nix#1]
Well, yeah, as the title. I'm trying to figure out what exactly this is :)

**Comment by ehmry** [comment]
This is "Nix on Genode", the Nix language, with breaking changes to most everything else.

**Comment by ehmry** [comment]
If someone were ~~clueless~~ nice enough to port systemd maybe it can be "NixOS on Genode"
